"""added date to RateTrackAssociation

Revision ID: a72d27a0e591
Revises: c2b7f8e8a63e
Create Date: 2023-12-06 16:22:38.236651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72d27a0e591'
down_revision = 'c2b7f8e8a63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates_track_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates_track_association', schema=None) as batch_op:
        batch_op.drop_column('rated_at')

    # ### end Alembic commands ###
